  NAME: 'EMA Crossover'
  MODULE: 'ema_crossover'
  CLASS: 'EMAcrossOver'
  INTERVAL: '1h'
  PERIOD: 300
  RISK_PC: 5
  SIZING: 'risk'
  PARAMETERS:
    slow_ema: 50
    fast_ema: 21
    RR: 2.0

  # Define pairs to monitor
  WATCHLIST: ['USDJPY=X']