NAME: 'Portfolio Rebalance'
MODULE: 'portfolio_rebalance'
CLASS: 'Rebalance'
INTERVAL: '1d'
PERIOD: 300
INCLUDE_BROKER: True
PARAMETERS:
  rebalance_every_N_days: 30
  rebalance_percentages:
    ETH-USD: 40
    BTC-USD: 40
    BNB-USD: 20
    # VAS.AX: 40 # %
    # VGS.AX: 40 # %
    # VGB.AX: 20
  rebalance_pc_tolerance: 0 # % 
  account_leverage: 1
  partial_trade_rounding: 1 # Round trade size to 1 decimal

WATCHLIST: ['ETH-USD','BTC-USD','BNB-USD']
  #           'VAS.AX',
  #           'VGS.AX',
  #           'VGB.AX']